# Generated by Django 5.1.1 on 2024-09-25 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('resId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('resName', models.CharField(max_length=50)),
                ('resLocation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('foodId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=50)),
                ('foodPrice', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.restaurant')),
            ],
        ),
    ]
